models:
  multilingual_e5: intfloat/multilingual-e5-large
#  minilm: sentence-transformers/all-MiniLM-L6-v2
#  mpnet_paraphrase: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
#  mpnet: sentence-transformers/all-mpnet-base-v2